# Manipulación de arreglos

In [2]:
import numpy as np
import random as r

In [3]:
lista = [r.randint(1,10) for _ in range(10)]
lista

[8, 6, 1, 6, 6, 8, 6, 9, 5, 2]

In [5]:
for i, e in enumerate(lista):
    print(i, e)

0 8
1 6
2 1
3 6
4 6
5 8
6 6
7 9
8 5
9 2


In [6]:
for e in iter(lista):
    print(e)

8
6
1
6
6
8
6
9
5
2


In [9]:
array = np.random.randint(0,10, 10)
array

array([0, 7, 6, 4, 2, 8, 4, 0, 0, 2], dtype=int32)

In [10]:
for x in array:
    print(x)

0
7
6
4
2
8
4
0
0
2


In [32]:
lista = [r.randint(1,11) for _ in range(10)]
lista 

[2, 2, 9, 8, 5, 5, 10, 6, 11, 6]

In [11]:
array2 = np.random.randint(1,10, (3,4))
array2

array([[4, 0, 6, 3],
       [2, 3, 5, 4],
       [5, 0, 5, 2]], dtype=int32)

In [28]:
for e in array2:
    print(e)

[4 0 6 3]
[2 3 5 4]
[5 0 5 2]


In [31]:
for e1 in array2:
    for e2 in e1:
        print(e2, end=' ')
    print()

4 0 6 3 
2 3 5 4 
5 0 5 2 


In [33]:
array3 = np.random.randint(1,11,(2,3,4))
array3

array([[[ 3,  2,  5,  2],
        [ 4,  9, 10,  4],
        [ 4, 10,  9,  8]],

       [[10,  8,  3,  4],
        [ 5,  4,  7,  4],
        [ 3,  7,  8, 10]]], dtype=int32)

In [35]:
for e in np.nditer(array3):
    print(e, end=' ')

3 2 5 2 4 9 10 4 4 10 9 8 10 8 3 4 5 4 7 4 3 7 8 10 

In [36]:
# Elevados al cuadrado
for e in np.nditer(array3):
    print(e**2, end=' ')

9 4 25 4 16 81 100 16 16 100 81 64 100 64 9 16 25 16 49 16 9 49 64 100 

In [39]:
for i, e in np.ndenumerate(array3):
    print(i, e)

(0, 0, 0) 3
(0, 0, 1) 2
(0, 0, 2) 5
(0, 0, 3) 2
(0, 1, 0) 4
(0, 1, 1) 9
(0, 1, 2) 10
(0, 1, 3) 4
(0, 2, 0) 4
(0, 2, 1) 10
(0, 2, 2) 9
(0, 2, 3) 8
(1, 0, 0) 10
(1, 0, 1) 8
(1, 0, 2) 3
(1, 0, 3) 4
(1, 1, 0) 5
(1, 1, 1) 4
(1, 1, 2) 7
(1, 1, 3) 4
(1, 2, 0) 3
(1, 2, 1) 7
(1, 2, 2) 8
(1, 2, 3) 10
