In [1]:
import numpy as np

In [2]:
matriz = np.random.randint(0, 101, size = (10,10))

In [3]:
matriz

array([[ 47, 100,  32,   8,  16,  20,  98,  57,  14,  61],
       [ 35,  67,  97,  60,  37,  15,  36,  80,   5,  69],
       [  5,  10,  82,  67,  97,  68,  48,  90,  97,  59],
       [ 49,   6,  23,  91,  56,  62,  90,  92,  26,  89],
       [ 97,  47,  66,   3,  88,  66, 100,  59,  57,   2],
       [ 23,  77,  66,  87,  51,  57,  15,  28,  60,  74],
       [ 63,  96,  64,  92,   4,  20,   4,  62,  32,  64],
       [ 52,   8,  98,  85,  76,  88,  45,  31,  19,  48],
       [ 10,  28,  72,  24,  17,  14, 100,  60,  84,  33],
       [  8,  68,  63,  61,  52,   8,  81,  56,  51,   8]], dtype=int32)

In [14]:
# Ultimas cuatro filas
matriz[0:3, :]

array([[ 47, 100,  32,   8,  16,  20,  98,  57,  14,  61],
       [ 35,  67,  97,  60,  37,  15,  36,  80,   5,  69],
       [  5,  10,  82,  67,  97,  68,  48,  90,  97,  59]], dtype=int32)

In [6]:
matriz[6: , :]

array([[ 63,  96,  64,  92,   4,  20,   4,  62,  32,  64],
       [ 52,   8,  98,  85,  76,  88,  45,  31,  19,  48],
       [ 10,  28,  72,  24,  17,  14, 100,  60,  84,  33],
       [  8,  68,  63,  61,  52,   8,  81,  56,  51,   8]], dtype=int32)

In [13]:
# Ultimas cuatro filas PRO
matriz[-4: , :]

array([[ 63,  96,  64,  92,   4,  20,   4,  62,  32,  64],
       [ 52,   8,  98,  85,  76,  88,  45,  31,  19,  48],
       [ 10,  28,  72,  24,  17,  14, 100,  60,  84,  33],
       [  8,  68,  63,  61,  52,   8,  81,  56,  51,   8]], dtype=int32)

In [16]:
# Filas impares
matriz[1::2, :]

array([[35, 67, 97, 60, 37, 15, 36, 80,  5, 69],
       [49,  6, 23, 91, 56, 62, 90, 92, 26, 89],
       [23, 77, 66, 87, 51, 57, 15, 28, 60, 74],
       [52,  8, 98, 85, 76, 88, 45, 31, 19, 48],
       [ 8, 68, 63, 61, 52,  8, 81, 56, 51,  8]], dtype=int32)

In [15]:
# Filas pares
matriz[::2, :]

array([[ 47, 100,  32,   8,  16,  20,  98,  57,  14,  61],
       [  5,  10,  82,  67,  97,  68,  48,  90,  97,  59],
       [ 97,  47,  66,   3,  88,  66, 100,  59,  57,   2],
       [ 63,  96,  64,  92,   4,  20,   4,  62,  32,  64],
       [ 10,  28,  72,  24,  17,  14, 100,  60,  84,  33]], dtype=int32)

In [18]:
# Ultima columna
matriz[:, -1:]

array([[61],
       [69],
       [59],
       [89],
       [ 2],
       [74],
       [64],
       [48],
       [33],
       [ 8]], dtype=int32)

In [20]:
# Columnas 5 y 6
matriz[:, 5:7]

array([[ 20,  98],
       [ 15,  36],
       [ 68,  48],
       [ 62,  90],
       [ 66, 100],
       [ 57,  15],
       [ 20,   4],
       [ 88,  45],
       [ 14, 100],
       [  8,  81]], dtype=int32)

In [21]:
# Columnas pares, filas impares
matriz[1::2, ::2]

array([[35, 97, 37, 36,  5],
       [49, 23, 56, 90, 26],
       [23, 66, 51, 15, 60],
       [52, 98, 76, 45, 19],
       [ 8, 63, 52, 81, 51]], dtype=int32)

In [19]:
matriz

array([[ 47, 100,  32,   8,  16,  20,  98,  57,  14,  61],
       [ 35,  67,  97,  60,  37,  15,  36,  80,   5,  69],
       [  5,  10,  82,  67,  97,  68,  48,  90,  97,  59],
       [ 49,   6,  23,  91,  56,  62,  90,  92,  26,  89],
       [ 97,  47,  66,   3,  88,  66, 100,  59,  57,   2],
       [ 23,  77,  66,  87,  51,  57,  15,  28,  60,  74],
       [ 63,  96,  64,  92,   4,  20,   4,  62,  32,  64],
       [ 52,   8,  98,  85,  76,  88,  45,  31,  19,  48],
       [ 10,  28,  72,  24,  17,  14, 100,  60,  84,  33],
       [  8,  68,  63,  61,  52,   8,  81,  56,  51,   8]], dtype=int32)

In [23]:
subMatriz = matriz[1::2, ::2]
subMatriz

array([[35, 97, 37, 36,  5],
       [49, 23, 56, 90, 26],
       [23, 66, 51, 15, 60],
       [52, 98, 76, 45, 19],
       [ 8, 63, 52, 81, 51]], dtype=int32)

In [27]:
subMatriz[0,0] = -111

In [28]:
matriz

array([[  47,  100,   32,    8,   16,   20,   98,   57,   14,   61],
       [-111,   67,   97,   60,   37,   15,   36,   80,    5,   69],
       [   5,   10,   82,   67,   97,   68,   48,   90,   97,   59],
       [  49,    6,   23,   91,   56,   62,   90,   92,   26,   89],
       [  97,   47,   66,    3,   88,   66,  100,   59,   57,    2],
       [  23,   77,   66,   87,   51,   57,   15,   28,   60,   74],
       [  63,   96,   64,   92,    4,   20,    4,   62,   32,   64],
       [  52,    8,   98,   85,   76,   88,   45,   31,   19,   48],
       [  10,   28,   72,   24,   17,   14,  100,   60,   84,   33],
       [   8,   68,   63,   61,   52,    8,   81,   56,   51,    8]],
      dtype=int32)

In [29]:
# 
matriz[::3, ::4]

array([[47, 16, 14],
       [49, 56, 26],
       [63,  4, 32],
       [ 8, 52, 51]], dtype=int32)

In [35]:
# matriz invertida de las filas 3 al 6 al 
matriz[7:3:-1, 7:3:-1]

array([[ 31,  45,  88,  76],
       [ 62,   4,  20,   4],
       [ 28,  15,  57,  51],
       [ 59, 100,  66,  88]], dtype=int32)

In [36]:
arreglo = [1,2,3,4,5,6,7,8,9]

In [37]:
arreglo[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [41]:
arreglo[3:8]
arreglo[3:8:-1]
arreglo[8:3:-1]

[9, 8, 7, 6, 5]