# Operaciones logicas con arreglos

In [1]:
import numpy as np

In [7]:
arreglo1 = np.array([3, 12, 15, 16, 3])
arreglo1

array([ 3, 12, 15, 16,  3])

In [8]:
arreglo2 = np.array([12, 3, 8, 7, 2])
arreglo2

array([12,  3,  8,  7,  2])

In [9]:
arreglo_and = np.bitwise_and(arreglo1, arreglo2)
arreglo_and

array([0, 0, 8, 0, 2])

In [10]:
arreglo_or = np.bitwise_or(arreglo1, arreglo2)
arreglo_or

array([15, 15, 15, 23,  3])

In [12]:
arreglo_xor = np.bitwise_xor(arreglo1, arreglo2)
arreglo_xor

array([15, 15,  7, 23,  1])

In [14]:
# tener cuidado pq se muere xd
arreglo_not = np.bitwise_not(arreglo1)
arreglo_not

array([ -4, -13, -16, -17,  -4])