# Como unir arreglos 

In [1]:
import numpy as np

In [3]:
unos = np.ones(5)
unos

array([1., 1., 1., 1., 1.])

In [4]:
ceros = np.zeros(5)
ceros

array([0., 0., 0., 0., 0.])

In [6]:
unos, ceros, np.concat((unos, ceros))

(array([1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]))

In [13]:
matriz1 = np.random.randint(0, 100, (3,3))
matriz1

array([[32,  2, 88],
       [42,  4, 92],
       [50, 99, 43]], dtype=int32)

In [12]:
matriz2 = np.random.randint(0, 100, (3,3))
matriz2

array([[80, 35, 13],
       [66, 83, 20],
       [97, 51, 65]], dtype=int32)

In [17]:
matriz1, matriz2, "-", np.stack((matriz1, matriz2), axis=1)

(array([[32,  2, 88],
        [42,  4, 92],
        [50, 99, 43]], dtype=int32),
 array([[80, 35, 13],
        [66, 83, 20],
        [97, 51, 65]], dtype=int32),
 '-',
 array([[[32,  2, 88],
         [80, 35, 13]],
 
        [[42,  4, 92],
         [66, 83, 20]],
 
        [[50, 99, 43],
         [97, 51, 65]]], dtype=int32))

In [22]:
matriz1, matriz2, "-", np.stack((matriz1, matriz2), axis=0)

(array([[32,  2, 88],
        [42,  4, 92],
        [50, 99, 43]], dtype=int32),
 array([[80, 35, 13],
        [66, 83, 20],
        [97, 51, 65]], dtype=int32),
 '-',
 array([[[32,  2, 88],
         [42,  4, 92],
         [50, 99, 43]],
 
        [[80, 35, 13],
         [66, 83, 20],
         [97, 51, 65]]], dtype=int32))