# Busqueda y ordenamiento

In [1]:
import numpy as np

In [7]:
aleatorios = np.random.randint(1, 10, 20)
aleatorios

array([7, 6, 6, 6, 4, 7, 7, 7, 1, 2, 1, 4, 2, 1, 8, 5, 1, 7, 6, 2],
      dtype=int32)

In [9]:
aleatorios, np.where(aleatorios == 2)

(array([7, 6, 6, 6, 4, 7, 7, 7, 1, 2, 1, 4, 2, 1, 8, 5, 1, 7, 6, 2],
       dtype=int32),
 (array([ 9, 12, 19]),))

In [10]:
np.where(aleatorios % 2 == 0)

(array([ 1,  2,  3,  4,  9, 11, 12, 14, 18, 19]),)

## ordenar con sort

In [11]:
np.sort(aleatorios)

array([1, 1, 1, 1, 2, 2, 2, 4, 4, 5, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8],
      dtype=int32)

In [13]:
matriz = np.random.randint(1, 10, (4,5))
matriz

array([[8, 1, 4, 2, 7],
       [8, 3, 7, 1, 6],
       [1, 4, 1, 7, 1],
       [6, 1, 9, 2, 7]], dtype=int32)

In [14]:
np.sort(matriz)

array([[1, 2, 4, 7, 8],
       [1, 3, 6, 7, 8],
       [1, 1, 1, 4, 7],
       [1, 2, 6, 7, 9]], dtype=int32)

In [15]:
np.sort(matriz, axis=0)

array([[1, 1, 1, 1, 1],
       [6, 1, 4, 2, 6],
       [8, 3, 7, 2, 7],
       [8, 4, 9, 7, 7]], dtype=int32)