# U Functions

In [1]:
import numpy as np

In [3]:
a1 = np.arange(1, 11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a2 = np.random.randint(1, 10, 10)
a2

array([5, 5, 9, 2, 5, 8, 9, 7, 9, 2], dtype=int32)

In [6]:
np.add(a1, a2)

array([ 6,  7, 12,  6, 10, 14, 16, 15, 18, 12])

In [9]:
a1, a2, np.sum(a1), np.sum(a2)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([5, 5, 9, 2, 5, 8, 9, 7, 9, 2], dtype=int32),
 np.int64(55),
 np.int64(61))

In [11]:
matriz = np.random.randint(1, 10, (3, 4))
matriz

array([[8, 4, 6, 4],
       [2, 1, 2, 9],
       [4, 2, 5, 1]], dtype=int32)

In [12]:
np.sum(matriz)

np.int64(48)

In [15]:
# suma por filas          suma por columnas
np.sum(matriz, axis=1), np.sum(matriz, axis=0)

(array([22, 14, 12]), array([14,  7, 13, 14]))

In [30]:
cubo = np.arange(1, 28).reshape(3,3,3)
cubo

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [31]:
np.sum(cubo)

np.int64(378)

In [32]:
np.prod(a1)

np.int64(3628800)

In [34]:
np.multiply(a1, a2)

array([ 5, 10, 27,  8, 25, 48, 63, 56, 81, 20])

In [35]:
a1*a2

array([ 5, 10, 27,  8, 25, 48, 63, 56, 81, 20])

In [36]:
np.log2(a1)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])