In [1]:
import numpy as np

In [2]:
# Tensor de 5 dimensiones de puros ceros
np.zeros((4,4,4,4,4), dtype = int)

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]],


        [[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]],


        [[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0,

In [3]:
# Matriz de 3x5 incializada con 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [4]:
np.full((4,6), 11)

array([[11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11]])

In [5]:
# Lo mismo que range, pero sobre los arreglos de numpy
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# Arreglo con los numeros impares desde el 7 hasta el 25
np.arange(7, 26, 2)

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [7]:
# Toma el intervalo dado (REAL) y se divide entre el numero de elementos indicados
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# De 0 a 100 entre 15
np.linspace(0, 100, 15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [11]:
# De 0 a 100 20
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [13]:
# Matriz de 3x3 generada con numeros aleatorios con distribucion uniforme
np.random.random((3,3))

array([[0.95156932, 0.79862938, 0.97528429],
       [0.37522162, 0.80763758, 0.08454375],
       [0.26352331, 0.70289901, 0.84222064]])

In [14]:
np.random.random((3,3,3))

array([[[0.95067555, 0.15863937, 0.18633055],
        [0.56760336, 0.36465853, 0.60584055],
        [0.71684325, 0.53796236, 0.02191042]],

       [[0.70045165, 0.67586496, 0.14876102],
        [0.55840207, 0.6331104 , 0.55267699],
        [0.07592666, 0.16369102, 0.23485935]],

       [[0.51784027, 0.59691786, 0.2448255 ],
        [0.54172999, 0.90593243, 0.83732571],
        [0.87496898, 0.05656056, 0.19372701]]])

In [20]:
lista = [2,2]
np.random.random(lista)
# Primer elemento que recibe es un 

array([[0.27801098, 0.1746079 ],
       [0.72230519, 0.36449166]])

In [21]:
# Matriz identidad 5x5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# direcciones de memoria donde estan los vectores vacios
direcciones = np.empty(3)

In [27]:
for direccion in direcciones:
    print(hex(id(direccion)))

0x1ebedc46230
0x1ebedc46190
0x1ebedc46230


In [6]:
# Generar la semilla del los numeros 
np.random.seed(0)

In [13]:
# Tensor unidimensional  
x1 = np.random.randint(10, size = 6)
x1

array([3, 5, 2, 4, 7, 6], dtype=int32)

In [9]:
print(x1)
print(type(x1))

[5 0 3 3 7 9]
<class 'numpy.ndarray'>


In [16]:
# Tensor bidimensional de numeros aleatorios con distribucion uniforme entre 10 y 20
# con tamaño 3, 4
x2 = np.random.randint(10, 20, size = (3,4))

In [17]:
x2

array([[14, 13, 10, 13],
       [15, 10, 12, 13],
       [18, 11, 13, 13]], dtype=int32)

In [18]:
# Tensor de tres dimensiones 
x3 = np.random.randint(10, size = (3,4,5))

In [19]:
x3

array([[[3, 7, 0, 1, 9],
        [9, 0, 4, 7, 3],
        [2, 7, 2, 0, 0],
        [4, 5, 5, 6, 8]],

       [[4, 1, 4, 9, 8],
        [1, 1, 7, 9, 9],
        [3, 6, 7, 2, 0],
        [3, 5, 9, 4, 4]],

       [[6, 4, 4, 3, 4],
        [4, 8, 4, 3, 7],
        [5, 5, 0, 1, 5],
        [9, 3, 0, 5, 0]]], dtype=int32)

In [20]:
x3[1,2,3]

np.int32(2)

In [22]:
# Imprimir atributos del tensor x1
print(f"x1 -> Dim: {x1.ndim}, Shape: {x1.shape}, Size: {x1.size}")
print(f"x1 -> {type(x1.ndim)}, {type(x1.shape)}, {type(x1.size)}")

x1 -> Dim: 1, Shape: (6,), Size: 6
x1 -> <class 'int'>, <class 'tuple'>, <class 'int'>
