# Intercambio de columnas

In [1]:
import numpy as np

In [17]:
# Tensor de 2 dimensiones con 4 filas y 4 columnas
aleatorios = np.arange(1, 17).reshape(4, 4)
aleatorios

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
# Transpuesta de una matriz
np.transpose(aleatorios)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [21]:
# Intercambio de columnas 1 y 3
aleatorios[:, [1,3]] = aleatorios[:, [3,1]]
aleatorios

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

array([[ 1,  5,  9, 13],
       [ 4,  8, 12, 16],
       [ 3,  7, 11, 15],
       [ 2,  6, 10, 14]])

In [7]:
# Checar version de Numpy
np.__version__

'2.1.1'