# Agregacion de elementos a un array

In [1]:
import numpy as np

In [3]:
array1 = np.ones(3, dtype='int16')
array1

array([1, 1, 1], dtype=int16)

In [12]:
array2 = np.zeros(3, dtype='int16')
array2

array([0, 0, 0], dtype=int16)

In [13]:
# Lista con 2 elementos que son arreglos de numpy
array3 = [array1, array2]
array3

[array([1, 1, 1], dtype=int16), array([0, 0, 0], dtype=int16)]

In [14]:
# Unir dos arreglos con append
array4 = np.append(array1, array2)
array4

array([1, 1, 1, 0, 0, 0], dtype=int16)

In [18]:
# Array de randoms flotantes
array5 = np.random.random(3)
array5

array([0.28171114, 0.92518174, 0.47820836])

In [19]:
# Append transforma en flotantes los enteros para no perder informacion de los flotantes random
array6 = np.append(array1, array5)
array6

array([1.        , 1.        , 1.        , 0.28171114, 0.92518174,
       0.47820836])

In [23]:
# Arreglo de caracteres
array7 = np.array(['a', 'b', 'c'], dtype='<U1')
array7

array(['a', 'b', 'c'], dtype='<U1')

In [24]:
# Append convierte los decimales en cadena para no perder info y que no se muera
array8 = np.append(array5, array7)
array8

array(['0.281711136302809', '0.9251817434570355', '0.47820836034368974',
       'a', 'b', 'c'], dtype='<U32')

In [30]:
# Reformar el array 1 para que ahora sea de dos dimensiones
array11 = array1.reshape(1, 3)
array11

array([[1, 1, 1]], dtype=int16)

In [31]:
# Reformar el array 2 para que ahora sea de dos dimensiones
array22 = array2.reshape(1, 3)
array22

array([[0, 0, 0]], dtype=int16)

In [37]:
# Concatena los dos arrays de dos dimensiones, uno debajo del otro
SuperArray = np.append(array11, array22, axis=0)
SuperArray

array([[1, 1, 1],
       [0, 0, 0]], dtype=int16)

In [38]:
# Tensor de dos dimensiones
prueba1 = np.arange(1,13).reshape(3,4)
prueba1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
# Tensor 2 dim

# normal(media, desviacion, numeroElementos)
prueba2 = np.random.normal(0,1,4).reshape(1,4)
prueba2

array([[ 0.60395953, -2.12904809,  0.92603322, -0.56152344]])

In [46]:
prueba3 = np.append(prueba1, prueba2)
prueba3

array([ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
        6.        ,  7.        ,  8.        ,  9.        , 10.        ,
       11.        , 12.        ,  0.60395953, -2.12904809,  0.92603322,
       -0.56152344])

In [47]:
prueba4 = np.append(prueba1, prueba2, axis=0)
prueba4

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ],
       [ 9.        , 10.        , 11.        , 12.        ],
       [ 0.60395953, -2.12904809,  0.92603322, -0.56152344]])

In [51]:
prueba5 = np.random.normal(100, 2, 12).reshape(3,4)
prueba5

array([[100.05915852,  99.4261062 ,  97.09354486, 100.97230578],
       [ 99.27410894, 103.35458421,  99.43451134, 100.8835117 ],
       [104.4835684 ,  99.61703307,  99.23440823, 101.19455219]])

In [52]:
prueba6 = np.append(prueba1, prueba5)
prueba6

array([  1.        ,   2.        ,   3.        ,   4.        ,
         5.        ,   6.        ,   7.        ,   8.        ,
         9.        ,  10.        ,  11.        ,  12.        ,
       100.05915852,  99.4261062 ,  97.09354486, 100.97230578,
        99.27410894, 103.35458421,  99.43451134, 100.8835117 ,
       104.4835684 ,  99.61703307,  99.23440823, 101.19455219])

In [53]:
prueba7 = np.append(prueba1, prueba5, axis=0)
prueba7

array([[  1.        ,   2.        ,   3.        ,   4.        ],
       [  5.        ,   6.        ,   7.        ,   8.        ],
       [  9.        ,  10.        ,  11.        ,  12.        ],
       [100.05915852,  99.4261062 ,  97.09354486, 100.97230578],
       [ 99.27410894, 103.35458421,  99.43451134, 100.8835117 ],
       [104.4835684 ,  99.61703307,  99.23440823, 101.19455219]])