# Brodcasting

In [2]:
import numpy as np
import random as sepalachingada

In [6]:
lista = [sepalachingada.randint(1,11) for _ in range(10)]
lista 

[4, 4, 11, 5, 3, 2, 9, 2, 4, 8]

In [7]:
lista + 5

TypeError: can only concatenate list (not "int") to list

In [8]:
resultado = []
for elemento in lista:
    resultado.append(elemento + 5)
resultado

[9, 9, 16, 10, 8, 7, 14, 7, 9, 13]

## Ejemplo 1

In [9]:
# Brodcasing tensor de 1 dim con escalar
a = np.arange(3)
a

array([0, 1, 2])

In [11]:
resultado = a + 5
resultado

array([5, 6, 7])

## Ejemplo 2

In [22]:
aleatorios = np.random.randint(1, 11, (3,4))
aleatorios

array([[ 9,  6,  3,  6],
       [10,  2,  4,  2],
       [ 6, 10,  5,  4]], dtype=int32)

In [23]:
resultado2 = aleatorios * 10
resultado2

array([[ 90,  60,  30,  60],
       [100,  20,  40,  20],
       [ 60, 100,  50,  40]], dtype=int32)

## Ejemplo 3 - cubo de unos

In [26]:
cubo_unos = np.ones((3,3,3), dtype="int16")
cubo_unos

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [27]:
resultado3 = cubo_unos + 2
resultado3

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]], dtype=int16)

In [28]:
resultado3[0,0,0] = 0
resultado3

array([[[0, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]], dtype=int16)

In [29]:
cubo_unos

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

## Ejemplo 4 matriz aleatorios

In [31]:
aleatorios, a

(array([[ 9,  6,  3,  6],
        [10,  2,  4,  2],
        [ 6, 10,  5,  4]], dtype=int32),
 array([0, 1, 2]))

In [34]:
r4 = aleatorios + a

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [36]:
c = np.arange(4)
c

array([0, 1, 2, 3])

In [39]:
r5 = aleatorios + c
aleatorios, c, r5

(array([[ 9,  6,  3,  6],
        [10,  2,  4,  2],
        [ 6, 10,  5,  4]], dtype=int32),
 array([0, 1, 2, 3]),
 array([[ 9,  7,  5,  9],
        [10,  3,  6,  5],
        [ 6, 11,  7,  7]]))

In [42]:
a2 = a.reshape(3,1)
a2

array([[0],
       [1],
       [2]])

In [43]:
r6 = aleatorios + a2
aleatorios, a2, r6

(array([[ 9,  6,  3,  6],
        [10,  2,  4,  2],
        [ 6, 10,  5,  4]], dtype=int32),
 array([[0],
        [1],
        [2]]),
 array([[ 9,  6,  3,  6],
        [11,  3,  5,  3],
        [ 8, 12,  7,  6]]))

## Ejemplo de brodcasting dificil jskjksa

In [45]:
k = a2 + a
a, a2, k

(array([0, 1, 2]),
 array([[0],
        [1],
        [2]]),
 array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]]))

In [50]:
a, c

(array([0, 1, 2]), array([0, 1, 2, 3]))

In [51]:
a + c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [52]:
a2 + c

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [55]:
pan = np.array([1, 2, 3])
ke = np.array([10, 20, 30])
pan, ke

(array([1, 2, 3]), array([10, 20, 30]))

In [56]:
pan + ke

array([11, 22, 33])