# Indexado avanzado 

In [1]:
import numpy as np

In [3]:
aleatorios = np.random.randint(0,101, (5,5))
aleatorios

array([[30, 22, 75, 84,  1],
       [72, 35, 80, 93, 10],
       [44, 68, 58, 64, 26],
       [86, 10, 47, 34, 53],
       [71, 18,  4, 88, 68]], dtype=int32)

In [4]:
aleatorios[3]

array([86, 10, 47, 34, 53], dtype=int32)

In [5]:
aleatorios[:, 2]

array([75, 80, 58, 47,  4], dtype=int32)

In [6]:
aleatorios[::2, ::2]

array([[30, 75,  1],
       [44, 58, 26],
       [71,  4, 68]], dtype=int32)

In [7]:
# Indexado avanzado
aleatorios[[0,1,4], :]

array([[30, 22, 75, 84,  1],
       [72, 35, 80, 93, 10],
       [71, 18,  4, 88, 68]], dtype=int32)

In [8]:
print(aleatorios)
aleatorios[[0,1,2], [1,2,3]]

[[30 22 75 84  1]
 [72 35 80 93 10]
 [44 68 58 64 26]
 [86 10 47 34 53]
 [71 18  4 88 68]]


array([22, 80, 64], dtype=int32)

# Mapping

In [9]:
# Aplicar condiciones a un solo arreglo
aleatorios < 50

array([[ True,  True, False, False,  True],
       [False,  True, False, False,  True],
       [ True, False, False, False,  True],
       [False,  True,  True,  True, False],
       [False,  True,  True, False, False]])

In [10]:
aleatorios[aleatorios < 50 ]

array([30, 22,  1, 35, 10, 44, 26, 10, 47, 34, 18,  4], dtype=int32)

In [14]:
#  Mapping con dos condiciones
(aleatorios > 15) & (aleatorios <= 30)

array([[ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False, False]])

In [13]:
aleatorios[(aleatorios > 15) & (aleatorios <= 30)]

array([30, 22, 26, 18], dtype=int32)

In [15]:
aleatorios.size

25

In [16]:
aleatorios[aleatorios != 10].size

23

In [17]:
# Ya que son conjuntos disjuntos y la inteseccion es el vacio
aleatorios[(aleatorios < 10) & (aleatorios > 90)].size

0

In [18]:
# Usando el operador OR
aleatorios[(aleatorios < 10) | (aleatorios > 90)].size

3